services:
  - type: web
    name: ludo-kingdom-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8403232282:AAGXrSzIciS5aEQSUJMs-iZ82LuTtEGBa8o
